/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// VersionMetadata struct for VersionMetadata
type VersionMetadata struct {
	Id          string            `json:"id"`
	Kind        string            `json:"kind"`
	Href        string            `json:"href"`
	Collections []ObjectReference `json:"collections,omitempty"`
}
