/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// VersionMetadataAllOf struct for VersionMetadataAllOf
type VersionMetadataAllOf struct {
	Collections []ObjectReference `json:"collections,omitempty"`
}
