/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// PhotoListAllOf struct for PhotoListAllOf
type PhotoListAllOf struct {
	Items []Photo `json:"items,omitempty"`
}
