/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// TagRequestPayload struct for TagRequestPayload
type TagRequestPayload struct {
	// name of the tag
	Name string `json:"name"`
	// hex rerepresentation of the color
	Color string `json:"color,omitempty"`
}
