/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// UserAllOf struct for UserAllOf
type UserAllOf struct {
	// name of the user
	Name string `json:"name,omitempty"`
	// surname of the user
	Surname string `json:"surname,omitempty"`
	// user_id
	UserId string            `json:"user_id,omitempty"`
	Groups []ObjectReference `json:"groups,omitempty"`
}
