/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// AlbumPermissionsAllOf struct for AlbumPermissionsAllOf
type AlbumPermissionsAllOf struct {
	Album  ObjectReference `json:"album,omitempty"`
	Users  []Permissions   `json:"users,omitempty"`
	Groups []Permissions   `json:"groups,omitempty"`
}
