/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// UserListAllOf struct for UserListAllOf
type UserListAllOf struct {
	Items []User `json:"items,omitempty"`
}
