/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// Photo struct for Photo
type Photo struct {
	Id    string          `json:"id"`
	Kind  string          `json:"kind"`
	Href  string          `json:"href"`
	Album ObjectReference `json:"album"`
	// path to the thumbnail of the photo
	Thumbnail string `json:"thumbnail"`
}
