/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// GroupAllOf struct for GroupAllOf
type GroupAllOf struct {
	// name of the group
	Name    string            `json:"name,omitempty"`
	Members []ObjectReference `json:"members,omitempty"`
}
