/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// AlbumPermissions struct for AlbumPermissions
type AlbumPermissions struct {
	Id     string          `json:"id"`
	Kind   string          `json:"kind"`
	Href   string          `json:"href"`
	Album  ObjectReference `json:"album"`
	Users  []Permissions   `json:"users,omitempty"`
	Groups []Permissions   `json:"groups,omitempty"`
}
