/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// PhotoAllOf struct for PhotoAllOf
type PhotoAllOf struct {
	Album ObjectReference `json:"album,omitempty"`
	// path to the thumbnail of the photo
	Thumbnail string `json:"thumbnail,omitempty"`
}
