/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// ErrorAllOf struct for ErrorAllOf
type ErrorAllOf struct {
	Code   int32  `json:"code"`
	Reason string `json:"reason,omitempty"`
}
