/*
 * gphotos
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: #VERSION#
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

// Error struct for Error
type Error struct {
	Id     string `json:"id"`
	Kind   string `json:"kind"`
	Href   string `json:"href"`
	Code   int32  `json:"code"`
	Reason string `json:"reason,omitempty"`
}
